const LOWERCASE_A_VALUE = 97;
const UPPERCASE_A_VALUE = 65;
const DIFFERENCE_LOWERCASE_UPPERCASE = LOWERCASE_A_VALUE - UPPERCASE_A_VALUE;
const NUMBER_OF_LETTERS = 26;

module.exports = {
	DIFFERENCE_LOWERCASE_UPPERCASE,
	LOWERCASE_A_VALUE,
	NUMBER_OF_LETTERS,
	UPPERCASE_A_VALUE
};
